"""add chain_head

Revision ID: 1885ab8782a2
Revises: 331ec198da8a
Create Date: 2026-06-21 14:30:02.032409
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1885ab8782a2'
down_revision: Union[str, None] = '331ec198da8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chain_head',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chain_head')
    # ### end Alembic commands ###
