"""add seen_nonces

Revision ID: 331ec198da8a
Revises: 372afb96f500
Create Date: 2026-06-18 02:12:50.620849
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '331ec198da8a'
down_revision: Union[str, None] = '372afb96f500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seen_nonces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nonce')
    )
    op.create_index(op.f('ix_seen_nonces_agent_id'), 'seen_nonces', ['agent_id'], unique=False)
    op.create_index(op.f('ix_seen_nonces_created_at'), 'seen_nonces', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seen_nonces_created_at'), table_name='seen_nonces')
    op.drop_index(op.f('ix_seen_nonces_agent_id'), table_name='seen_nonces')
    op.drop_table('seen_nonces')
    # ### end Alembic commands ###
