"""alert dedup columns

Revision ID: 61f62372980c
Revises: 1885ab8782a2
Create Date: 2026-06-21 15:04:51.132082
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '61f62372980c'
down_revision: Union[str, None] = '1885ab8782a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('dedup_key', sa.String(length=160), nullable=True))
    # server_default='1' -> dolu tablolarda NOT NULL eklemesi güvenli olur.
    op.add_column('alerts', sa.Column('count', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('alerts', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_alerts_dedup_key'), 'alerts', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_alerts_last_seen'), 'alerts', ['last_seen'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_last_seen'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_dedup_key'), table_name='alerts')
    op.drop_column('alerts', 'last_seen')
    op.drop_column('alerts', 'count')
    op.drop_column('alerts', 'dedup_key')
    # ### end Alembic commands ###
